### ISSUE TITLE
İts Not Openning I tried build too but its not opening heres the log:

### ISSUE THREAD

**Issue by hackeroyuncu09** [Retro64Mod/Retro64Mod.github.io#104]
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.UnsupportedClassVersionError: cpw/mods/modlauncher/Launcher has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getLibraryDir(IFileDetector.java:55)
	at io.github.zekerzhayard.forgewrapper.installer.detector.MultiMCFileDetector.getLibraryDir(MultiMCFileDetector.java:24)
	at io.github.zekerzhayard.forgewrapper.installer.detector.MultiMCFileDetector.getInstallerJar(MultiMCFileDetector.java:33)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:120)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:115)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:147)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:29)
	... 8 more
Exiting with -1

**Comment by dylanpdx** [comment]
Not a Retro64 issue
