### ISSUE TITLE
Server crashing in 1.0.9

### ISSUE THREAD

**Issue by Evanzap** [Retro64Mod/Retro64Mod.github.io#121]
Server crashes in 1.0.9 with only retro64 and its dependencies

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[fmlloader-1.18.2-40.0.44.jar%2316!/:1.0] {}
-- MOD retro64 --
Details:
        Caused by 0: java.lang.ExceptionInInitializerError
                at jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?] {}
                at jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160) ~[?:?] {}
                at jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300) ~[?:?] {}
                at jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103) ~[?:?] {}
                at jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:236) ~[?:?] {}
                at java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:546) ~[?:?] {}
                at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:496) ~[?:?] {}
                at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?] {}
                at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.2-40.0.44.jar%2343!/:?] {}
                at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.2-40.0.44.jar%2342!/:?] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
                at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
                at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
                at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

        Mod File: retro64-1.0.9.jar
        Failure message: Retro64 (retro64) has failed to load correctly
                java.lang.ExceptionInInitializerError: null
        Mod Version: 1.0.9
        Mod Issue URL: NOT PROVIDED
        Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/RenderType for invalid dist DEDICATED_SERVER
Stacktrace:
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[fmlloader-1.18.2-40.0.44.jar%2316!/:1.0] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] {}
        at com.dylanpdx.retro64.Retro64.<clinit>(Retro64.java:30) ~[retro64-1.0.9.jar%2339!/:1.0.9] {re:classloading}
        at jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?] {}
        at jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160) ~[?:?] {}
        at jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300) ~[?:?] {}
        at jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103) ~[?:?] {}
        at jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:236) ~[?:?] {}
        at java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:546) ~[?:?] {}
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:496) ~[?:?] {}
        at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.2-40.0.44.jar%2343!/:?] {}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.2-40.0.44.jar%2342!/:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
        Minecraft Version: 1.18.2
        Minecraft Version ID: 1.18.2
        Operating System: Windows 11 (amd64) version 10.0
        Java Version: 18, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
        Memory: 1155904000 bytes (1102 MiB) / 1744830464 bytes (1664 MiB) up to 8573157376 bytes (8176 MiB)
        CPUs: 6
        Processor Vendor: AuthenticAMD
        Processor Name: AMD Ryzen 5 3600 6-Core Processor
        Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
        Microarchitecture: Zen 2
        Frequency (GHz): 3.59
        Number of physical packages: 1
        Number of physical CPUs: 3
        Number of logical CPUs: 6
        Graphics card #0 name: NVIDIA GeForce GTX 1650
        Graphics card #0 vendor: NVIDIA (0x10de)
        Graphics card #0 VRAM (MB): 4095.00
        Graphics card #0 deviceId: 0x1f82
        Graphics card #0 versionInfo: DriverVersion=30.0.15.1215
        Memory slot #0 capacity (MB): 8192.00
        Memory slot #0 clockSpeed (GHz): 2.13
        Memory slot #0 type: DDR4
        Memory slot #1 capacity (MB): 8192.00
        Memory slot #1 clockSpeed (GHz): 2.13
        Memory slot #1 type: DDR4
        Memory slot #2 capacity (MB): 8192.00
        Memory slot #2 clockSpeed (GHz): 2.13
        Memory slot #2 type: DDR4
        Memory slot #3 capacity (MB): 8192.00
        Memory slot #3 clockSpeed (GHz): 2.13
        Memory slot #3 type: DDR4
        Virtual memory max (MB): 37558.45
        Virtual memory used (MB): 20729.09
        Swap memory total (MB): 4864.00
        Swap memory used (MB): 0.00
        JVM Flags: 0 total;
        ModLauncher: 9.1.3+9.1.3+main.9b69c82a
        ModLauncher launch target: forgeserver
        ModLauncher naming: srg
        ModLauncher services:
                 mixin PLUGINSERVICE
                 eventbus PLUGINSERVICE
                 slf4jfixer PLUGINSERVICE
                 object_holder_definalize PLUGINSERVICE
                 runtime_enum_extender PLUGINSERVICE
                 capability_token_subclass PLUGINSERVICE
                 accesstransformer PLUGINSERVICE
                 runtimedistcleaner PLUGINSERVICE
                 mixin TRANSFORMATIONSERVICE
                 OptiFine TRANSFORMATIONSERVICE
                 fml TRANSFORMATIONSERVICE
        FML Language Providers:
                minecraft@1.0
                javafml@null
        Mod List:
                server-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |COMMON_SET|Manifest: NOSIGNATURE
                forge-1.18.2-40.0.44-universal.jar                |Forge                         |forge                         |40.0.44             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
                retro64-1.0.9.jar                                 |Retro64                       |retro64                       |1.0.9               |ERROR     |Manifest: NOSIGNATURE
        Crash Report UUID: 7a8c8527-2b35-4c51-9a64-9e93041bdfec
        FML: 40.0
        Forge: net.minecraftforge:40.0.44[17:11:25] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Retro64 (retro64) has failed to load correctly
?7java.lang.ExceptionInInitializerError: null
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:235) ~[fmlcore-1.18.2-40.0.44.jar%2342!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:200) ~[fmlcore-1.18.2-40.0.44.jar%2342!/:?] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:200) ~[fmlcore-1.18.2-40.0.44.jar%2342!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:177) ~[fmlcore-1.18.2-40.0.44.jar%2342!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:177) ~[fmlcore-1.18.2-40.0.44.jar%2342!/:?] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.18.2-40.0.44-universal.jar%2345!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%2341!/:?] {re:classloading}
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46) ~[fmlloader-1.18.2-40.0.44.jar%2316!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

**Comment by dylanpdx** [comment]
Please check if the following jar file fixes the issue: https://github.com/Retro64Mod/Retro64Mod/actions/runs/2425154212
(you may need to be logged into GitHub to download it)

**Comment by Evanzap** [comment]
it worked! thank you

**Comment by dylanpdx** [comment]
No problem, I'll hopefully have this released publicly within a day
