### ISSUE TITLE
Crashes with error -1

### ISSUE THREAD

**Issue by Mineblox99** [Retro64Mod/Retro64Mod.github.io#155]
** Bug Name**
When I open it, it loads but when the title screen is supposed to show it just crashes and says the files are null and the error code is NEGATIVE ONE -1 

**To Reproduce**
1. Open the mod
2. let it crash
**Minecraft Version**
1.18.2

**Mod Version**
Latest

**Minecraft launcher**
Curseforge

**Please attach Screenshots or Crash logs if relevant to the bug**
[crash-2022-11-16_10.15.15-client.txt](https://github.com/Retro64Mod/Retro64Mod.github.io/files/10023811/crash-2022-11-16_10.15.15-client.txt)
[crash-2022-11-16_10.21.40-client.txt](https://github.com/Retro64Mod/Retro64Mod.github.io/files/10023812/crash-2022-11-16_10.21.40-client.txt)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version 10

**Additional context**
I tried everything but nothing works. It just closes.
Latest log:
[latest.log](https://github.com/Retro64Mod/Retro64Mod.github.io/files/10024440/latest.log)
or just [10:21:12] [main/INFO]: ModLauncher running: args [--username, HeadedHat361, --version, forge-40.1.0, --gameDir, C:\Users\Lucas\curseforge\minecraft\Instances\retro64, --assetsDir, C:\Users\Lucas\curseforge\minecraft\Install\assets, --assetIndex, 1.18, --uuid, 10c162037aaf4087a7f63d7c4e23ce52, --accessToken, ????????, --clientId, Y2I5ZmU3YmQtYzlkNi00OTFhLWI5ZDUtODEyYzhmNzZiNTRh, --xuid, 2535437352871146, --userType, msa, --versionType, release, --width, 1024, --height, 768, --launchTarget, forgeclient, --fml.forgeVersion, 40.1.0, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[10:21:12] [main/INFO]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft
[10:21:12] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Lucas/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
[10:21:12] [main/INFO]: Found mod file retro64-1.0.10.jar of type MOD with locator {mods folder locator at C:\Users\Lucas\curseforge\minecraft\Instances\retro64\mods}
[10:21:13] [main/INFO]: Found mod file fmlcore-1.18.2-40.1.0.jar of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3704122f
[10:21:13] [main/INFO]: Found mod file javafmllanguage-1.18.2-40.1.0.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3704122f
[10:21:13] [main/INFO]: Found mod file mclanguage-1.18.2-40.1.0.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3704122f
[10:21:13] [main/INFO]: Found mod file client-1.18.2-20220404.173914-srg.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3704122f
[10:21:13] [main/INFO]: Found mod file forge-1.18.2-40.1.0-universal.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3704122f
[10:21:14] [main/INFO]: Compatibility level set to JAVA_17
[10:21:14] [main/INFO]: Launching target 'forgeclient' with arguments [--version, forge-40.1.0, --gameDir, C:\Users\Lucas\curseforge\minecraft\Instances\retro64, --assetsDir, C:\Users\Lucas\curseforge\minecraft\Install\assets, --uuid, 10c162037aaf4087a7f63d7c4e23ce52, --username, HeadedHat361, --assetIndex, 1.18, --accessToken, ????????, --clientId, Y2I5ZmU3YmQtYzlkNi00OTFhLWI5ZDUtODEyYzhmNzZiNTRh, --xuid, 2535437352871146, --userType, msa, --versionType, release, --width, 1024, --height, 768]
[10:21:20] [Render thread/WARN]: Assets URL 'union:/C:/Users/Lucas/curseforge/minecraft/Install/libraries/net/minecraft/client/1.18.2-20220404.173914/client-1.18.2-20220404.173914-srg.jar%2353!/assets/.mcassetsroot' uses unexpected schema
[10:21:20] [Render thread/WARN]: Assets URL 'union:/C:/Users/Lucas/curseforge/minecraft/Install/libraries/net/minecraft/client/1.18.2-20220404.173914/client-1.18.2-20220404.173914-srg.jar%2353!/data/.mcassetsroot' uses unexpected schema
[10:21:20] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10:21:21] [Render thread/INFO]: Setting user: HeadedHat361
[10:21:21] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
[10:21:23] [modloading-worker-0/INFO]: Forge mod loading, version 40.1.0, for MC 1.18.2 with MCP 20220404.173914
[10:21:23] [modloading-worker-0/INFO]: MinecraftForge v40.1.0 Initialized
[10:21:25] [Render thread/INFO]: Narrator library for x64 successfully loaded
[10:21:25] [Render thread/INFO]: Reloading ResourceManager: Default, Mod Resources
[10:21:26] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[10:21:26] [Forge Version Check/INFO]: [forge] Found status: UP_TO_DATE Current: 40.1.0 Target: null
[10:21:38] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (Realtek(R) Audio)
[10:21:38] [Render thread/INFO]: Sound engine started
[10:21:38] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[10:21:38] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[10:21:38] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[10:21:38] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[10:21:38] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[10:21:38] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[10:21:38] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[10:21:39] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[10:21:39] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[10:21:39] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[10:21:39] [Render thread/ERROR]: Exception caught during firing event: Cannot read the array length because "files" is null
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: com.dylanpdx.retro64.events.clientEvents@17665f93 onScreenShown(Lnet/minecraftforge/client/event/ScreenOpenEvent;)V
java.lang.NullPointerException: Cannot read the array length because "files" is null
	at TRANSFORMER/retro64@1.0.10/com.dylanpdx.retro64.SM64EnvManager.getROMFile(SM64EnvManager.java:216)
	at TRANSFORMER/retro64@1.0.10/com.dylanpdx.retro64.events.clientEvents.onScreenShown(clientEvents.java:628)
	at net.minecraftforge.eventbus.ASMEventHandler_7_clientEvents_onScreenShown_ScreenOpenEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91152_(Minecraft.java:907)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:561)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.Util.m_137521_(Util.java:397)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:549)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:877)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

[10:21:40] [Render thread/ERROR]: Exception caught during firing event: Cannot read the array length because "files" is null
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: com.dylanpdx.retro64.events.clientEvents@17665f93 onScreenShown(Lnet/minecraftforge/client/event/ScreenOpenEvent;)V
java.lang.NullPointerException: Cannot read the array length because "files" is null
	at TRANSFORMER/retro64@1.0.10/com.dylanpdx.retro64.SM64EnvManager.getROMFile(SM64EnvManager.java:216)
	at TRANSFORMER/retro64@1.0.10/com.dylanpdx.retro64.events.clientEvents.onScreenShown(clientEvents.java:628)
	at net.minecraftforge.eventbus.ASMEventHandler_7_clientEvents_onScreenShown_ScreenOpenEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91152_(Minecraft.java:907)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91362_(Minecraft.java:2156)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91320_(Minecraft.java:2124)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91394_(Minecraft.java:1185)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:681)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

[10:21:40] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.ReportedException: Rendering overlay
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:884) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.0.jar%2316!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: java.lang.NullPointerException: Cannot read the array length because "files" is null
	at com.dylanpdx.retro64.SM64EnvManager.getROMFile(SM64EnvManager.java:216) ~[retro64-1.0.10.jar%2352!/:1.0.10]
	at com.dylanpdx.retro64.events.clientEvents.onScreenShown(clientEvents.java:628) ~[retro64-1.0.10.jar%2352!/:1.0.10]
	at net.minecraftforge.eventbus.ASMEventHandler_7_clientEvents_onScreenShown_ScreenOpenEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraft.client.Minecraft.m_91152_(Minecraft.java:907) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?]
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:561) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?]
	at net.minecraft.Util.m_137521_(Util.java:397) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?]
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:549) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?]
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:877) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?]
	... 16 more
[10:21:40] [Render thread/FATAL]: Preparing crash report with UUID 0db9ba9f-6be4-4586-934c-d7192c91c91b
[10:21:40] [Render thread/FATAL]: Preparing crash report with UUID 8e1b97b0-6a50-464a-a361-123a81740705

**Comment by dylanpdx** [comment]
Working on a fix for this

**Comment by dylanpdx** [comment]
Fixed on https://github.com/Retro64Mod/Retro64Mod/releases/tag/1.18.2-1.0.12
