### ISSUE TITLE
invalid memory adress

### ISSUE THREAD

**Issue by LuigiMario1** [Retro64Mod/Retro64Mod.github.io#192]
**Describe the bug**

**To Reproduce**
1. press m

**Minecraft Version**
1.18.2 forge

**Mod Version**
1.0.13

**Minecraft launcher**
vanilla

**Please attach Screenshots or Crash logs if relevant to the bug**

**Desktop (please complete the following information):**
 - OS: windows
 - Version 10

**Additional context**
invalid memory adress
[crash-2023-06-13_02.05.46-client.txt](https://github.com/Retro64Mod/Retro64Mod.github.io/files/11731185/crash-2023-06-13_02.05.46-client.txt)

**Comment by LuigiMario1** [comment]
i turned off defender

**Comment by LuigiMario1** [comment]
- Minecraft Crash Report ----
// You're mean.

Time: 6/13/23, 2:05 AM
Description: Unexpected error

java.lang.Error: Invalid memory access
	at com.sun.jna.Native.invokeVoid(Native Method) ~[jna-5.10.0.jar%2351!/:5.10.0 (b0)] {}
	at com.sun.jna.Function.invoke(Function.java:415) ~[jna-5.10.0.jar%2351!/:5.10.0 (b0)] {}
	at com.sun.jna.Function.invoke(Function.java:361) ~[jna-5.10.0.jar%2351!/:5.10.0 (b0)] {}
	at com.sun.jna.Library$Handler.invoke(Library.java:265) ~[jna-5.10.0.jar%2351!/:5.10.0 (b0)] {}
	at com.sun.jna.Native$3.invoke(Native.java:1252) ~[jna-5.10.0.jar%2351!/:5.10.0 (b0)] {}
	at jdk.proxy3.$Proxy34.sm64_mChar_tick(Unknown Source) ~[?:?] {}
	at com.dylanpdx.retro64.sm64.libsm64.LibSM64.MCharTick(LibSM64.java:123) ~[retro64-1.0.9.jar%2352!/:1.0.9] {re:classloading}
	at com.dylanpdx.retro64.sm64.libsm64.MChar.fixedUpdate(MChar.java:89) ~[retro64-1.0.9.jar%2352!/:1.0.9] {re:classloading}
	at com.dylanpdx.retro64.sm64.libsm64.MChar.<init>(MChar.java:79) ~[retro64-1.0.9.jar%2352!/:1.0.9] {re:classloading}
	at com.dylanpdx.retro64.RemoteMCharHandler.mCharOn(RemoteMCharHandler.java:86) ~[retro64-1.0.9.jar%2352!/:1.0.9] {re:mixin,re:classloading}
	at com.dylanpdx.retro64.RemoteMCharHandler.toggleMChar(RemoteMCharHandler.java:141) ~[retro64-1.0.9.jar%2352!/:1.0.9] {re:mixin,re:classloading}
	at com.dylanpdx.retro64.events.clientEvents.gameTick(clientEvents.java:82) ~[retro64-1.0.9.jar%2352!/:1.0.9] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_2_clientEvents_gameTick_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreClientTick(ForgeEventFactory.java:902) ~[forge-1.18.2-40.1.16-universal.jar%2357!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1614) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1019) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.16.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.sun.jna.Native.invokeVoid(Native Method) ~[jna-5.10.0.jar%2351!/:5.10.0 (b0)] {}
	at com.sun.jna.Function.invoke(Function.java:415) ~[jna-5.10.0.jar%2351!/:5.10.0 (b0)] {}
	at com.sun.jna.Function.invoke(Function.java:361) ~[jna-5.10.0.jar%2351!/:5.10.0 (b0)] {}
	at com.sun.jna.Library$Handler.invoke(Library.java:265) ~[jna-5.10.0.jar%2351!/:5.10.0 (b0)] {}
	at com.sun.jna.Native$3.invoke(Native.java:1252) ~[jna-5.10.0.jar%2351!/:5.10.0 (b0)] {}
	at jdk.proxy3.$Proxy34.sm64_mChar_tick(Unknown Source) ~[?:?] {}
	at com.dylanpdx.retro64.sm64.libsm64.LibSM64.MCharTick(LibSM64.java:123) ~[retro64-1.0.9.jar%2352!/:1.0.9] {re:classloading}
	at com.dylanpdx.retro64.sm64.libsm64.MChar.fixedUpdate(MChar.java:89) ~[retro64-1.0.9.jar%2352!/:1.0.9] {re:classloading}
	at com.dylanpdx.retro64.sm64.libsm64.MChar.<init>(MChar.java:79) ~[retro64-1.0.9.jar%2352!/:1.0.9] {re:classloading}
	at com.dylanpdx.retro64.RemoteMCharHandler.mCharOn(RemoteMCharHandler.java:86) ~[retro64-1.0.9.jar%2352!/:1.0.9] {re:mixin,re:classloading}
	at com.dylanpdx.retro64.RemoteMCharHandler.toggleMChar(RemoteMCharHandler.java:141) ~[retro64-1.0.9.jar%2352!/:1.0.9] {re:mixin,re:classloading}
	at com.dylanpdx.retro64.events.clientEvents.gameTick(clientEvents.java:82) ~[retro64-1.0.9.jar%2352!/:1.0.9] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_2_clientEvents_gameTick_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreClientTick(ForgeEventFactory.java:902) ~[forge-1.18.2-40.1.16-universal.jar%2357!/:?] {re:classloading}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['LuigiMario_120'/71, l='ClientLevel', x=-2.50, y=-60.00, z=4.50]]
	Chunk stats: 961, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 251 game time, 251 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:407) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2255) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.16.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 704813472 bytes (672 MiB) / 1476395008 bytes (1408 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1660 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x21c4
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3598
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 22066.66
	Virtual memory used (MB): 15849.69
	Swap memory total (MB): 14157.09
	Swap memory used (MB): 1352.85
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.18.2-forge-40.1.16
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 535.98, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['LuigiMario_120'/71, l='ServerLevel[New World]', x=-2.50, y=-60.00, z=4.50]]
	Data Packs: vanilla, mod:forge (incompatible), mod:retro64 (incompatible)
	World Generation: Stable
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.18.2-40.1.16-universal.jar                |Forge                         |forge                         |40.1.16             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		retro64-1.0.9.jar                                 |Retro64                       |retro64                       |1.0.9               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: aa8454b8-78fc-4d9d-a1c9-a8e61dc37819
	FML: 40.1
	Forge: net.minecraftforge:40.1.16

**Comment by dylanpdx** [comment]
Do you have the ROM in the mods folder?

**Comment by LuigiMario1** [comment]
yes

**Comment by LuigiMario1** [comment]
its a us rom

**Comment by LuigiMario1** [comment]
![image](https://github.com/Retro64Mod/Retro64Mod.github.io/assets/133192394/08cc7088-a984-4500-9c62-41d2bd66fd1c)

**Comment by LuigiMario1** [comment]
help

**Comment by LuigiMario1** [comment]
it was the rom
